apiVersion: v2
appVersion: "1.0"
description: A Helm chart for st-wa-task-configuration
name: sptribs-task-configuration
home: https://github.com/hmcts/st-wa-task-configuration
version: 0.0.4
maintainers:
  - name: HMCTS ST team
dependencies:
  - name: java
    version: 5.2.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: ccd
    version: 8.0.29
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    tags:
      - ccd-idam-pr
  - name: xui-webapp
    version: ~1.0.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: xui-webapp.enabled
  - name: idam-pr
    version: 2.3.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: idam-pr.enabled
  - name: camunda-bpm
    version: 0.0.28
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: camunda-bpm.enabled
