apiVersion: v2
appVersion: "1.0"
description: A Helm chart for st-wa-task-configuration
name: st-wa-task-configuration
home: https://github.com/hmcts/st-wa-task-configuration
version: 0.0.4
maintainers:
  - name: HMCTS ST team
dependencies:
  - name: java
    version: 5.0.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: ccd
    version: 8.0.29
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    tags:
      - ccd-idam-pr
  - name: xui-webapp
    version: ~1.0.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: xui-webapp.enabled
  - name: xui-mo-webapp
    version: ~1.1.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: xui-mo-webapp.enabled
  - name: aac-manage-case-assignment
    version: ~0.2.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: aac-manage-case-assignment.enabled
  - name: idam-pr
    version: 2.3.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: idam-pr.enabled
  - name: ccd-case-document-am-api
    version: 1.7.14
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd-case-document-am-api.enabled
  - name: em-ccdorc
    version: 2.0.10
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: em-ccdorc.enabled
  - name: em-stitching
    version: 1.0.55
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: em-stitching.enabled
