tags:
  ccd-idam-pr: true

java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    IDAM_CLIENT_ID: sptribs_case_api
    CASE_DATA_STORE_BASEURL: http://{{ .Release.Name }}-ccd-data-store-api
    CASE_DOCUMENT_AM_BASEURL: http://${SERVICE_NAME}-ccd-case-document-am-api
    BUNDLING_API_URL: https://em-ccdorc-${SERVICE_FQDN}
    CITIZEN_UPDATE_CASE_STATE_ENABLED: true
    POSTGRES_HOST: ${SERVICE_NAME}-postgresql
    POSTGRES_NAME: sptribs-case-api
    POSTGRES_USERNAME: ${SPTRIBS_POSTGRES_USERNAME_PREVIEW}
    POSTGRES_PASSWORD: ${SPTRIBS_POSTGRES_PASSWORD_PREVIEW}
    POSTGRES_CONNECTION_OPTIONS: ""

  keyVaults:
    sptribs:
      secrets:
        - name: app-insights-instrumentation-key-preview
          alias: app-insights-instrumentation-key
        - name: app-insights-connection-string-preview
          alias: app-insights-connection-string
        - name: uk-gov-notify-api-key
          alias: UK_GOV_NOTIFY_API_KEY_1
        - name: s2s-case-api-secret
          alias: S2S_SECRET
        - name: idam-secret
          alias: IDAM_CLIENT_SECRET
        - name: idam-systemupdate-username
          alias: IDAM_SYSTEM_UPDATE_USERNAME
        - name: idam-systemupdate-password
          alias: IDAM_SYSTEM_UPDATE_PASSWORD
        - name: launchdarkly-sdk-key
          alias: LAUNCH_DARKLY_SDK_KEY
        - name: sptribs-postgres-username-preview
          alias: SPTRIBS_POSTGRES_USERNAME_PREVIEW
        - name: sptribs-postgres-password-preview
          alias: SPTRIBS_POSTGRES_PASSWORD_PREVIEW
        - name: ccd-global-postgres-username-preview
          alias: CCD_GLOBAL_POSTGRES_USERNAME_PREVIEW
        - name: ccd-global-postgres-password-preview
          alias: CCD_GLOBAL_POSTGRES_PASSWORD_PREVIEW
        - name: ccd-data-store-db-username-preview
          alias: CCD_DATA_STORE_DB_USERNAME_PREVIEW
        - name: ccd-data-store-db-password-preview
          alias: CCD_DATA_STORE_DB_PASSWORD_PREVIEW
        - name: ccd-user-profile-db-username-preview
          alias: CCD_USER_PROFILE_DB_USERNAME_PREVIEW
        - name: ccd-user-profile-db-password-preview
          alias: CCD_USER_PROFILE_DB_PASSWORD_PREVIEW
        - name: em-spring-datasource-username-preview
          alias: EM_SPRING_DATASOURCE_USERNAME_PREVIEW
        - name: em-spring-datasource-password-preview
          alias: EM_SPRING_DATASOURCE_PASSWORD_PREVIEW

  postgresql:
    enabled: true
    image:
      tag: '11.6.0'
    primary:
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 25m
      initdb:
        scripts:
          init.sql: |
            CREATE DATABASE "definition-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
            CREATE DATABASE "role_assignment" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
            CREATE DATABASE "user-profile" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
            CREATE DATABASE "camunda" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
    auth:
      username: ${SPTRIBS_POSTGRES_USERNAME_PREVIEW}
      password: ${SPTRIBS_POSTGRES_PASSWORD_PREVIEW}

ccd:
  ccd:
    definitionImporter:
      enabled: false
    apiGatewayWeb:
      enabled: true
    postgresql:
      enabled: false
    s2s:
      enabled: false
    elastic:
      enabled: true

  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}

  global:
    idamApiUrl: https://idam-api.aat.platform.hmcts.net
    idamWebUrl: https://idam-web-public.aat.platform.hmcts.net
    dmStoreUrl: http://dm-store-aat.service.core-compute-aat.internal
    ccdAdminWebIngress: admin-web-${SERVICE_FQDN}
    ccdApiGatewayIngress: gateway-${SERVICE_FQDN}
    postgresUsername: ${CCD_GLOBAL_POSTGRES_USERNAME_PREVIEW}
    postgresPassword: ${CCD_GLOBAL_POSTGRES_PASSWORD_PREVIEW}
    s2sUrl: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal

  ccd-api-gateway-web:
    nodejs:
      disableKeyVaults: true
      imagePullPolicy: Always
      environment:
        ADDRESS_LOOKUP_TOKEN: ${ADDRESS_LOOKUP_TOKEN}
        IDAM_SERVICE_KEY: ${CCD_API_GATEWAY_S2S_KEY}
        IDAM_OAUTH2_CLIENT_SECRET: ${CCD_API_GATEWAY_OAUTH2_CLIENT_SECRET}
        PROXY_DOCUMENT_MANAGEMENT: http://dm-store-aat.service.core-compute-aat.internal
      ingressHost: gateway-${SERVICE_FQDN}
      ingressIP: ${INGRESS_IP}

  ccd-data-store-api:
    java:
      imagePullPolicy: Always
      environment:
        CASE_DOCUMENT_AM_API_ATTACH_DOCUMENT_ENABLED: true
        DATA_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DATA_STORE_DB_USERNAME: ${CCD_DATA_STORE_DB_USERNAME_PREVIEW}
        DATA_STORE_DB_PASSWORD: ${CCD_DATA_STORE_DB_PASSWORD_PREVIEW}
        DATA_STORE_IDAM_KEY: ${DATA_STORE_S2S_KEY}
        DATA_STORE_DEFAULT_LOG_LEVEL: info
        LOG_CALLBACK_DETAILS: "*"
        DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_gw,ccd_gateway,ccd_data,aac_manage_case_assignment,xui_webapp,ccd_case_document_am_api,sptribs_frontend,sptribs_case_api,em_ccd_orchestrator
        CCD_S2S_AUTHORISED_SERVICES_CASE_USER_ROLES: aac_manage_case_assignment,fpl_case_service,finrem_case_orchestration,iac,sptribs_frontend,civil_service,sptribs_case_api
        ELASTIC_SEARCH_ENABLED: true
        ELASTIC_SEARCH_HOSTS: ${SERVICE_NAME}-es-master:9200
        ELASTIC_SEARCH_DATA_NODES_HOSTS: http://${SERVICE_NAME}-es-master:9200
        CCD_DM_DOMAIN: http://dm-store-aat.service.core-compute-aat.internal
        CCD_DOCUMENT_URL_PATTERN: ^https?://(((?:api-gateway\.preprod\.dm\.reform\.hmcts\.net|dm-store-aat\.service\.core-compute-aat\.internal(?::\d+)?)\/documents\/[A-Za-z0-9-]+(?:\/binary)?)|(em-hrs-api-aat\.service\.core-compute-aat\.internal(?::\d+)?\/hearing-recordings\/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\/segments\/[0-9]))
        IDAM_API_BASE_URL: https://idam-api.aat.platform.hmcts.net
        IDAM_OIDC_URL: https://idam-web-public.aat.platform.hmcts.net
        OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat.internal:8443/openam/oauth2/hmcts
        CASE_DOCUMENT_AM_URL: http://${SERVICE_NAME}-ccd-case-document-am-api
        IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET: ${IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET}
        IDAM_DATA_STORE_SYSTEM_USER_USERNAME: ${IDAM_DATA_STORE_SYSTEM_USER_USERNAME}
        IDAM_DATA_STORE_SYSTEM_USER_PASSWORD: ${IDAM_DATA_STORE_SYSTEM_USER_PASSWORD}
        ROLE_ASSIGNMENT_URL: http://sptribs-case-api-pr-${CHANGE_ID}-am-role-assignment-service
      keyVaults:
        ccd:
          secrets:
            - name: data-store-api-POSTGRES-USER-V15
              alias: DATA_STORE_DB_USERNAME
            - name: data-store-api-POSTGRES-PASS-V15
              alias: DATA_STORE_DB_PASSWORD
            - name: data-store-api-draft-key
              alias: CCD_DRAFT_ENCRYPTION_KEY
            - name: ccd-data-s2s-secret
              alias: DATA_STORE_IDAM_KEY
            - name: ccd-ELASTIC-SEARCH-URL
              alias: ELASTIC_SEARCH_HOSTS
            - name: ccd-ELASTIC-SEARCH-DATA-NODES-URL
              alias: ELASTIC_SEARCH_DATA_NODES_HOSTS
            - name: ccd-ELASTIC-SEARCH-PASSWORD
              alias: ELASTIC_SEARCH_PASSWORD
            - name: app-insights-connection-string
              alias: app-insights-connection-string
            - name: idam-data-store-client-secret
              alias: IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET
            - name: idam-data-store-system-user-username
              alias: IDAM_DATA_STORE_SYSTEM_USER_USERNAME
            - name: idam-data-store-system-user-password
              alias: IDAM_DATA_STORE_SYSTEM_USER_PASSWORD
      ingressHost: ccd-data-store-api-${SERVICE_FQDN}
      autoscaling:
        enabled: false

  am-role-assignment-service:
    java:
      disableKeyVaults: true
      environment:
        CCD_DATA_STORE_URL: http://{{ .Release.Name }}-ccd-data-store-api
        RUN_LD_ON_STARTUP: false

  ccd-definition-store-api:
    java:
      disableKeyVaults: true
      imagePullPolicy: Always
      environment:
        DEFINITION_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DEFINITION_STORE_IDAM_KEY: ${DEFINITION_STORE_S2S_KEY}
        IDAM_USER_URL: https://idam-web-public.aat.platform.hmcts.net
        ELASTIC_SEARCH_ENABLED: true
        ELASTIC_SEARCH_HOST: ${SERVICE_NAME}-es-master
      ingressHost: ccd-definition-store-${SERVICE_FQDN}
      autoscaling:
        enabled: false
    postgresql:
      persistence:
        enabled: false

  ccd-user-profile-api:
    java:
      disableKeyVaults: true
      imagePullPolicy: Always
      enviroment:
        USER_PROFILE_DB_HOST: ${SERVICE_NAME}-postgresql
      ingressHost: ccd-user-profile-api-${SERVICE_FQDN}

  ccd-admin-web:
    nodejs:
      disableKeyVaults: true
      image: hmctspublic.azurecr.io/ccd/admin-web:latest
      ingressHost: admin-web-${SERVICE_FQDN}
      environment:
        USER_PROFILE_DB_HOST: ${SERVICE_NAME}-postgresql
        IDAM_ADMIN_WEB_SERVICE_KEY: ${ADMIN_S2S_KEY}
        IDAM_OAUTH2_AW_CLIENT_SECRET: ${ADMIN_WEB_IDAM_SECRET}

  importer:
    userprofile:
      enabled: true
      jurisdictions:
        - ST_CIC
      users:
        - st_caseworker@mailinator.com|ST_CIC|CIC|Submitted
        - st_solicitor@mailinator.com|ST_CIC|CIC|Submitted
        - st_super@mailinator.com|ST_CIC|CIC|Submitted
      userProfileDatabaseHost: ${SERVICE_NAME}-ccd-postgres
      userProfileDatabasePort: 5432
      userProfileDatabaseUser: ${CCD_USER_PROFILE_DB_USERNAME_PREVIEW}
      userProfileDatabasePassword: ${CCD_USER_PROFILE_DB_PASSWORD_PREVIEW}
      userProfileDatabaseName: user-profile

xui-webapp:
  enabled: true
  nodejs:
    imagePullPolicy: Always
    releaseNameOverride: ${SERVICE_NAME}-xui-webapp
    image: hmctspublic.azurecr.io/xui/webapp:latest
    ingressHost: xui-${SERVICE_FQDN}
    devcpuRequests: 250m
    devmemoryRequests: 1024Mi
    devmemoryLimits: 1024Mi
    environment:
      SERVICES_CCD_COMPONENT_API: http://{{ .Release.Name }}-ccd-api-gw
      SERVICES_CCD_DATA_STORE_API: http://{{ .Release.Name }}-ccd-data-store-api
      SERVICES_DOCUMENTS_API_V2: http://${SERVICE_NAME}-ccd-case-document-am-api
      SERVICES_CCD_CASE_ASSIGNMENT_API: http://{{ .Release.Name }}-aac-manage-case-assignment
      JURISDICTIONS: ST_CIC,ST_CS,ST_MH,ST_PHL,ST_SEN,ST_DD
      CASE_TYPES: CIC,CS,MH,PHL,SEN,DD
      FEATURE_REDIS_ENABLED: false
      FEATURE_APP_INSIGHTS_ENABLED: true
      NODE_OPTIONS: --max-old-space-size=900
      HEALTH_ROLE_ASSIGNMENT_API: http://sptribs-case-api-pr-${CHANGE_ID}-am-role-assignment-service
      SERVICES_ROLE_ASSIGNMENT_API: http://sptribs-case-api-pr-${CHANGE_ID}-am-role-assignment-service

idam-pr:
  enabled: true
  releaseNameOverride: ${SERVICE_NAME}-idam-pr
  redirect_uris:
    XUI:
      - https://xui-${SERVICE_FQDN}/oauth2/callback
    XUIMO:
      - https://xui-mo-${SERVICE_FQDN}/oauth2/callback

camunda-bpm:
  enabled: true
  java:
    disableKeyVaults: true
    releaseNameOverride: ${SERVICE_NAME}-camunda
    ingressHost: camunda-${SERVICE_FQDN}
    imagePullPolicy: Always
    environment:
      CAMUNDA_API_AUTH_ENABLED: false
      CAMUNDA_DB_HOST: ${SERVICE_NAME}-postgresql
      CAMUNDA_DB_NAME: camunda
      CAMUNDA_DB_USER_NAME: hmcts
      CAMUNDA_DB_PASSWORD: hmcts
      CAMUNDA_BPM_DATABASE_SCHEMA_UPDATE: true
      S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      CAMUNDA_DB_CONN_OPTIONS: ""

